127466 alerts gui
equinor/radix-web-console pull request #445
Opened 2021-11-09 14:36 UTC by nilsgstrabo

2021-11-11 09:38 UTC, Pespiri requested changes

2021-11-11 09:38 UTC, Pespiri commented on src/components/alerting/edit-alerting.js
> +import * as React from 'react';
Avoid importing entire components where possible
```suggestion
import { useEffect, useState } from 'react';
```

2021-11-11 09:39 UTC, Pespiri commented
Also see if you can use a more modern pattern for the state (reducers and such)

2021-11-11 11:57 UTC, nilsgstrabo commented on src/components/alerting/alerting-overview.js
> +        </>
Fixed

2021-11-11 11:59 UTC, nilsgstrabo commented on src/components/alerting/edit-alerting.js
> +};
Fixed

2021-11-11 12:04 UTC, nilsgstrabo commented on src/components/alerting/edit-alerting.js
> +};
Fixed

2021-11-11 12:05 UTC, nilsgstrabo commented on src/components/alerting/edit-alerting.js
> +import * as React from 'react';
fixed

2021-11-11 12:50 UTC, Pespiri submitted a review, later dismissed

2021-11-16 08:50 UTC, Pespiri approved these changes

2021-11-16 08:54 UTC, merged