191147 add vulnerability scan information
equinor/radix-web-console pull request #538
Opened 2022-05-12 11:17 UTC by Pespiri

2022-05-16 09:06 UTC, nilsgstrabo requested changes
See if it is possible/easy to format columns when vulnerability summry is shown

2022-05-16 14:34 UTC, Pespiri commented on src/components/page-environment/component-list.tsx
> +                <Table className="component-list">
fixed

2022-05-16 14:34 UTC, Pespiri commented on src/components/page-environment/component-list.tsx
> +                <Table className="component-list">
fixed

2022-05-18 07:37 UTC, nilsgstrabo approved these changes

2022-05-18 07:38 UTC, merged