Fix large logs
equinor/radix-web-console pull request #568
Opened 2022-06-24 14:43 UTC by satr

2022-06-27 08:18 UTC, Pespiri requested changes

2022-06-27 08:18 UTC, Pespiri commented on src/components/page-step/job-step-logs.tsx
> +import { Accordion, Typography } from '@equinor/eds-core-react';
Sort imports, keep external libraries separated by newline from internal includes, import styles.css last

```suggestion
import { Accordion, Typography } from '@equinor/eds-core-react';
import * as PropTypes from 'prop-types';

import { useGetJobStepFullLogs } from './use-get-job-step-full-logs';
import { usePollJobStepLogs } from './use-poll-job-step-logs';
import AsyncResource from '../async-resource/simple-async-resource';
import { Log, LogDownloadOverrideType } from '../component/log';

import './style.css';
```

2022-06-27 08:18 UTC, Pespiri commented on src/components/page-step/job-step-logs.tsx
> +                ></Log>
Elements without children can be shortened

```suggestion
                <Log
                  downloadOverride={downloadOverride}
                  fileName={jobName + stepName + '.txt'}
                  logContent={pollStepLogsState.data}
                />
```

2022-06-27 08:18 UTC, Pespiri commented on src/components/page-step/index.tsx
> +              ></JobStepLogs>
Elements without children can be shortened

```suggestion
              <JobStepLogs
                appName={appName}
                jobName={jobName}
                stepName={stepName}
              />
```

2022-06-27 08:18 UTC, Pespiri commented on src/components/page-replica/index.tsx
> +          </>
Remove unneeded extra fragment tag

```suggestion
          <Replica
            logState={pollLogsState}
            replica={replica}
            downloadOverride={downloadOverride}
            title={
              <Typography>
                Replica <strong>{smallReplicaName(replicaName)}</strong>,
                component <strong>{componentName}</strong>
              </Typography>
            }
          />
```

2022-06-27 12:35 UTC, satr commented on src/components/page-step/index.tsx
>  import './style.css';
Fixed

2022-06-27 12:36 UTC, satr commented on src/components/page-step/index.tsx
>  import { Dispatch } from 'redux';
Fixed

2022-06-27 12:36 UTC, satr commented on src/components/page-step/index.tsx
>  import { mapRouteParamsToProps } from '../../utils/routing';
Fixed

2022-06-28 08:35 UTC, satr commented on src/components/page-replica/index.tsx
> -
Fixed

2022-06-28 08:46 UTC, satr commented on src/components/page-scheduled-job/index.tsx
> +import { useGetFullJobLogs } from './use-get-job-full-logs';
Fixed

2022-06-28 08:51 UTC, satr commented on src/components/page-scheduled-batch/index.tsx
> +import { useGetBatchFullLogs } from './use-get-batch-full-logs';
Fixed

2022-06-28 08:52 UTC, satr commented on src/components/page-step/index.tsx
> -
Fixed

2022-06-28 10:06 UTC, merged