259799 show identity federation info
equinor/radix-web-console pull request #673
Opened 2023-01-06 09:12 UTC by nilsgstrabo

2023-01-06 11:17 UTC, Pespiri requested changes

2023-01-06 11:49 UTC, nilsgstrabo commented on src/components/page-active-component/active-component-overview.tsx
> +import { EnvironmentModel } from '../../models/environment';
fixed

2023-01-06 12:05 UTC, nilsgstrabo commented on src/components/page-active-component/active-component-overview.tsx
> +  environment?: EnvironmentModel;
fixed

2023-01-06 12:13 UTC, nilsgstrabo commented on src/components/page-active-component/overview.tsx
> +  deployment: PropTypes.shape(DeploymentModelValidationMap).isRequired,
fixed

2023-01-06 12:21 UTC, nilsgstrabo commented on src/components/page-active-job-component/active-job-component-overview.tsx
> +  environment?: EnvironmentModel;
fixed

2023-01-06 12:25 UTC, nilsgstrabo commented on src/components/page-active-job-component/overview.js
> +  deployment: PropTypes.shape(DeploymentModelValidationMap).isRequired,
Deployment is required. A component cannot exist without a deployment.

2023-01-06 12:32 UTC, nilsgstrabo commented on src/models/component/index.ts
> +  identity?: IdentityModel;
fixed

2023-01-09 08:31 UTC, Pespiri approved these changes

2023-01-09 15:03 UTC, merged