update page environment
equinor/radix-web-console pull request #894
Opened 2023-12-11 07:27 UTC by Pespiri

2023-12-12 11:51 UTC, Richard87 commented
No events from API, And some errors in the console:
![image](https://github.com/equinor/radix-web-console/assets/5749715/d1d39184-7318-4702-a308-61a23c82e05d)

404 from Vulnerabilities 🤔 
![image](https://github.com/equinor/radix-web-console/assets/5749715/a60bde56-c03b-4296-828b-8de11beddf93)

data har feil type? Burde ikkje den vera `GetDeploymentsApiResponse|unefine` (frem til den er lastet inn?)
![image](https://github.com/equinor/radix-web-console/assets/5749715/f5f798ac-8f69-434c-a7ee-cc780660416c)

2023-12-12 11:51 UTC, Richard87 requested changes
Kan vi fikse console errors?

2023-12-12 12:05 UTC, Pespiri commented
404 er vanlig i local dev fra Scan API, bare noe man blir vant med.
Skal sjekke opp i den typen i Deployments du nevnte 🤔

2023-12-18 06:52 UTC, Pespiri commented
usikker på hva du mener med "Burde være \*Type\*/Undefined frem til den er lastet inn".
Typescript er ikke runtime.

404 fra Scan-Api er noe som ikke er kodens feil, og hører heller ikke til denne pull request'n.
bryr meg for lite til å se inn i dette, men kan fortelle deg det er API'ets feil

2023-12-18 08:35 UTC, Richard87 approved these changes
lgtm!

2023-12-18 09:19 UTC, Richard87 approved these changes
LGTM! :D

2023-12-18 09:20 UTC, merged